name: Build and deploy artifact

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun build ./wsserver.js --compile --outfile=ws-server-linux-x64 --target=bun-linux-x64-baseline
      # Upload
      - uses: actions/upload-artifact@v4
        with:
          name: ws-server-linux-x64
          path: ws-server-linux-x64
